language: java
jdk: oraclejdk11
script: "mvn sonar:sonar -Dsonar.projectKey=cezarcruz_loja-web -Dsonar.organization=cezarcruz-github -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login=f3468a27a117a6de7e9dffab6931ad8fa90203f5"
